[package]
name = "aoc_handler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dirs = "6.0.0"
itertools = "0.14.0"
rand = "0.9.2"
reqwest = {version = "0.13.1", features = ["blocking"]}
rust_decimal = "1.40.0"
thiserror = "2.0.18"
