[package]
name = "aoc_handler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
derive_more = {version = "1.0.0", features = ["from"]}
dirs = "5.0.1"
reqwest = {version = "0.12.9", features = ["blocking"]}
